name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --tag registry.cn-hongkong.aliyuncs.com/docker18099/fengdev:lento-latest
    - name: tag image
      run: docker tag registry.cn-hongkong.aliyuncs.com/docker18099/fengdev:lento-latest registry.cn-hongkong.aliyuncs.com/docker18099/fengdev:lento-$(date +%d%m%y)
    - name: login
      run: echo ${{ secrets.ALIYUN_DOCKER_REPO_PASSWD }} | docker login --username=inter18099@hotmail.com --password-stdin registry.cn-hongkong.aliyuncs.com
    - name: push
      run: docker push registry.cn-hongkong.aliyuncs.com/docker18099/fengdev:lento-$(date +%d%m%y)
    - name: push latest
      run: docker push registry.cn-hongkong.aliyuncs.com/docker18099/fengdev:lento-latest
